name: write_rawdata
language: python
variables:
  - name: input
    inputType: InputTopic
    description: This is the input topic
    defaultValue: rawdata
    required: true
  - name: INFLUXDB_HOST
    inputType: FreeText
    description: Host address for the InfluxDB instance.
    defaultValue: us-east-1-1.aws.cloud2.influxdata.com
    required: true
  - name: INFLUXDB_TOKEN
    inputType: FreeText
    description: Authentication token to access InfluxDB.
    defaultValue: otH27gQGb0_jfX23a97cSxgThgODChC-x1ScXaz_l4Bib_OgPRTgJulF_eCorb-ZJPsEp4DqM47xYrs7CVnkCA==
    required: true
  - name: INFLUXDB_ORG
    inputType: FreeText
    description: Organization name in InfluxDB.
    defaultValue: b2f03312964087cd
    required: false
  - name: INFLUXDB_DATABASE
    inputType: FreeText
    description: Database name in InfluxDB where data should be stored.
    defaultValue: iotanomalydetection
    required: true
  - name: INFLUXDB_TAG_COLUMNS
    inputType: FreeText
    description: Columns to be used as tags when writing data to InfluxDB.
    defaultValue: "['barcode', 'provider']"
    required: false
  - name: INFLUXDB_MEASUREMENT_NAME
    inputType: FreeText
    description: The InfluxDB measurement to write data to. If not specified, the name of the input topic will be used
    defaultValue: machine_data
    required: false
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
