name: MQTT
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to publish to.
    defaultValue: rawdata
    required: true
  - name: mqtt_topic
    inputType: FreeText
    description: The root for messages in MQTT, this can be anything
    defaultValue: machine/#
    required: true
  - name: mqtt_server
    inputType: FreeText
    description: The address of your MQTT server
    defaultValue: 5d419fcaa7ed4414971058fdef650db6.s1.eu.hivemq.cloud
    required: true
  - name: mqtt_port
    inputType: FreeText
    description: The port of your MQTT instance
    defaultValue: 8883
    required: true
  - name: mqtt_username
    inputType: FreeText
    description: Your MQTT username
    defaultValue: mgenio
    required: true
  - name: mqtt_version
    inputType: FreeText
    description: 'MQTT protocol version: 3.1, 3.1.1, 5'
    defaultValue: 3.1.1
    required: true
  - name: mqtt_password
    inputType: Secret
    description: ''
    defaultValue: 
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: mqtt_function.py
